products = [
    {
        "id": 1,
        "title": "Timbo Relaxing Chair",
        "brand": "Chenone",
        "category": "Furniture",
        "image": "/images/media/chair.webp",
        "description": "Modern style wooden Chair for  study room, living room",
        "price": "500",
        "stock": 8,
        "rating": "4.50",
        "createdAt": "2024-07-09T14:01:46.896045Z",
        "reviews": 0,
        "user": 0
    },
    {
        "id": 2,
        "title": "Azalea Pink Chair",
        "brand": "Urban store",
        "category": "seating",
        "image": "/images/media/3_3fe78c84-2d02-43e0-9372-59bd4757e2b9_1024x1024.webp",
        "description": "It includes thickly padded seat and curved back to give you maximum comfort. It is supported by four wooden legs which having a chestnut furnishing to add an extra style. The back rest has button tufts in it which are highly comfortable. • Its solid wooden legs make it study and luxurious addition to your spaces. A textured look to compliment any décor style.",
        "price": "28000",
        "stock": 30,
        "rating": "4.50",
        "createdAt": "2024-07-19T19:59:39.025982Z",
        "reviews": 20,
        "user": 1
    },
    {
        "id": 3,
        "title": "Frosty Peach Lounge Chair",
        "brand": "Urban store",
        "category": "seating",
        "image": "/images/media/14_47e024f7-714d-4d40-a1b4-7bfdce684b78_1024x1024.webp",
        "description": "This accent chair features a cushioned padding, making it an exceptional choice to curl you up with its geometrical patterned on peach background. It supported by four wooden chair legs which have veneer finishing on them. • A cozy elegant seat to add compliment for home styling. Add a touch of texture with this beautifully made frosty peach and flex.",
        "price": "38000",
        "stock": 40,
        "rating": "4.00",
        "createdAt": "2024-07-19T20:03:18.959520Z",
        "reviews": 14,
        "user": 1
    },
    {
        "id": 4,
        "title": "Lofitile Lounge Chair",
        "brand": "Urban store",
        "category": "seating",
        "image": "/images/media/WhatsAppImage2024-03-09at1.20.25PM_1024x1024.webp",
        "description": "A classy white chair for perfect lounge seating",
        "price": "42500",
        "stock": 20,
        "rating": "4.00",
        "createdAt": "2024-07-19T20:06:47.842127Z",
        "reviews": 15,
        "user": 1
    },
    {
        "id": 5,
        "title": "Hebisscus Lounge Chair",
        "brand": "Urban store",
        "category": "seating",
        "image": "/images/media/10_fdd7f7d8-9926-4524-87cd-fa74c0d78ea2_1024x1024.webp",
        "description": "With sophisticated design this chair includes upholstered soft plush seating supported with solid wood frame that shows your choice with its wide welcoming seat and wooden arms. • Bring the modern minimalist style that gives you comfortable seat to relax and natural texture to bring aesthetic chic vibes.",
        "price": "48000",
        "stock": 20,
        "rating": "4.50",
        "createdAt": "2024-07-19T20:10:06.082046Z",
        "reviews": 15,
        "user": 1
    },
    {
        "id": 6,
        "title": "Wetiny Pod Swing",
        "brand": "Urban store",
        "category": "Decor",
        "image": "/images/media/new-Pod-swing-8_1024x1024.webp",
        "description": "Iron stand and frame ( 16 Gauge)\r\nPlastic fiber basket\r\nWith cushions. (Cushions are removable)\r\nCan bear weight upto 100 kgs\r\nHeight: 6 ft\r\nWidth: 2.5-3 ft",
        "price": "16500",
        "stock": 20,
        "rating": "5.00",
        "createdAt": "2024-07-19T20:32:00.871924Z",
        "reviews": 20,
        "user": 1
    }
]